name: bot

services:

  trading-bot:
    container_name: trading-bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: python main.py

  add-balance-history:
    container_name: add-balance-history
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: python routine_add_balance_history.py
