name: Deploy to EC2 using ssh

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create known_hosts file
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${EC2_HOST} >> ~/.ssh/known_hosts
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}

      - name: Write SSH key to file
        run: |
          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/private_key
          chmod 600 ~/.ssh/private_key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Upload .env to EC2
        run: |
          echo ${DOTENV} > .env
          echo "DEBUG=0" >> .env
          scp -i ~/.ssh/private_key .env ${USER}@${EC2_HOST}:${WORKDIR}
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          STRATEGIES: ${{ secrets.STRATEGIES }}
          WORKDIR: ${{ secrets.WORKDIR }}
          USER: ${{ secrets.USER }}
          DOTENV: ${{ secrets.DOTENV }}

      - name: Upload strategies.py to EC2
        run: |
          echo "${STRATEGIES}" > strategies.py
          scp -i ~/.ssh/private_key strategies.py ${USER}@${EC2_HOST}:${WORKDIR}
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.USER }}
          STRATEGIES: ${{ secrets.STRATEGIES }}
          WORKDIR: ${{ secrets.WORKDIR }}
          
      - name: Deploy code to EC2
        run: |
          ssh -i ~/.ssh/private_key ${USER}@${EC2_HOST} <<'EOF'
          cd ~/code/trading-bot/
          git reset --hard HEAD
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          WORKDIR: ${{ secrets.WORKDIR }}
          USER: ${{ secrets.USER }}