name: Deploy to remote linux machine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Copy files to remote server
        run: |
          rsync -avz --exclude='.git' . ${{ secrets.USER }}@${{ secrets.HOST }}:${{ secrets.WORKDIR }}

      - name: Build and deploy with Docker Compose
        run: |
          ssh ${{ secrets.USER }}@${{ secrets.HOST }} << 'EOF'
          cd ${{ secrets.WORKDIR }}
          docker compose -f "docker-compose.yml" build
          EOF
